twitter-server: Avoids misleading errors for FlagResolver and TwitterResolver Problem
1) FlagResolver is misleading when something is missing from resolverMap.

> com.twitter.finagle.ResolverNotFoundException: Resolver not found for scheme
"mysvc". Please add the jar containing this resolver to your classpath

Note: mysvc *is* registered in the resolvermap.

2) TwitterResolver swallows real exceptions and give a misleading
ResolverNotFoundException

3) Network isolation was causing internally logged exceptions, which seemed to
be an error in ResolverTest

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  Operation that is
forbidden in tests attempted in thread
Thread[main-ScalaTest-running-ResolverTest,5,main]: attempted resolving host
xxxxxxx.twitter.com !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
com.twitter.common_internal.test_security.JUnitSecurityMgr$JUnitSecurityException:
Operation that is forbidden in tests attempted in thread
Thread[main-ScalaTest-running-ResolverTest,5,main]: attempted resolving host
xxxxxxx.twitter.com
	at
	com.twitter.common_internal.test_security.JUnitSecurityMgr.checkConnect(JUnitSecurityMgr.java:73)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1203) at
	java.net.InetAddress.getAllByName(InetAddress.java:1127) at
	java.net.InetAddress.getAllByName(InetAddress.java:1063) at
	java.net.InetAddress.getByName(InetAddress.java:1013) at
	java.net.InetSocketAddress.<init>(InetSocketAddress.java:142) at
	com.twitter.server.ServerSets$anonfun$defaultReadHosts$1.apply(ServerSets.scala:30)
	at
	com.twitter.server.ServerSets$anonfun$defaultReadHosts$1.apply(ServerSets.scala:30)
	at scala.Option.getOrElse(Option.scala:120) at
	com.twitter.server.ServerSets$.defaultReadHosts(ServerSets.scala:29) at
	com.twitter.server.ServerSets$.getDefaultReadHosts(ServerSets.scala:44)
	at
	com.twitter.server.ServerSets$anonfun$buildReadConfig$1.apply(ServerSets.scala:116)
	at
	com.twitter.server.ServerSets$anonfun$buildReadConfig$1.apply(ServerSets.scala:116)
	at com.twitter.server.ServerSets$.buildConfig(ServerSets.scala:80) at
	com.twitter.server.ServerSets$.buildReadConfig(ServerSets.scala:116) at
	com.twitter.server.ServerSetResolver$anonfun$2.apply(ServerSetResolver.scala:45)
	at
	com.twitter.server.ServerSetResolver$anonfun$2.apply(ServerSetResolver.scala:44)
	at scala.Option.flatMap(Option.scala:170) at
	com.twitter.server.ServerSetResolver.bind(ServerSetResolver.scala:44) at
	com.twitter.finagle.BaseResolver.eval(Resolver.scala:328) at
	com.twitter.server.ResolverTest$anonfun$9$anonfun$apply$mcV$sp$15$anonfun$apply$mcV$sp$16$anonfun$apply$mcV$sp$17.apply$mcV$sp(ResolverTest.scala:136)
	at com.twitter.app.Flag.let(Flag.scala:270)

Solution

1) FlagResolver uses a specific exception with a clear message

> com.twitter.server.NamedResolverNotFoundException: Resolver not found for
scheme 'flag' with name 'mysvc'. Registered resolvers mysvc1,mysvc2,mysvc3

2) TwitterResolver does not swallow exceptions and instead just calls straight
through to FlagResolver

Result

clients getting exceptions with correctly registered resolvers will get a
NamedResolverNotFoundException instead of ResolverNotFoundException

RB_ID=498845