Introduce a dependency on util-events
Problem

When building a basic TwitterServer application, a runtime error is encountered
on first run:

    java.lang.NoClassDefFoundError: com/twitter/util/events/Event$Type
      at com.twitter.server.EventSink$$anonfun$1.apply$mcV$sp(EventSink.scala:34)

Solution

Add a dependency on util-events

Signed-off-by: Christopher Coco <ccoco@twitter.com>

RB_ID=805557