Add deps on Guava 16.0.1 to twitter-server and finagle-http poms
Problem

com.twitter.finagle.http.codec.HttpDtab uses
com.google.common.io.BaseEncoding, which is in Guava 14+. Since
finagle-http does not depend directly on Guava, it gets v13.x from
Jackson, which lacks the BaseEncoding class. This results in
NoClassDefFoundErrors being thrown and e.g. TwitterServers failing
silently at runtime.

Solution

Add explicit dependencies on Guava 16.0.1 in finagle-http and
twitter-server.

RB_ID=440309